### ISSUE TITLE
Permission rules don't work as expected

### ISSUE THREAD

**Issue by hvorragend** [zikula-modules/Pages#1]
bug description

I want to grant access to pages in a category only to a special user group.
Members of "Nixen" should have access to pages in category "Nixen-Intern" (ID: 10038).
Members of "Lynn" should have access to pages in category "Lynn-Intern" (ID: 10038).
All users are member in Group "Users".

These are the permission rules that I entered in my Zikula instance:

Nixen    Pages:category:    10038::                        Read
Nixen    Pages::            ::17|19|21                     Read
Lynn     Pages:category:    10026::                        Read
Lynn     Pages::            ::9|10|11|18|20|24             Read
Users    Pages:category:    10026|10038::                  No access
Users    Pages::            ::9|10|11|17|18|19|20|21|24    No access
Users    .\*                 .\*                             Read

This works for members of group "Nixen" as it should.
But members of group "Lynn" can access pages in both categories.
bug analysis

As the problem exists only for members of "Lynn" I can imagine, that it has to do with old data (cache?).
Lynn had before acccess to category "Nixen-Intern". I recently created the new category "Lynn-Intern" and assigned some of the pages to it.

I can do further investigation in DB or filesystem, if you tell me, where to look.
fix recommendation

b.t.w. It is avoiding, that one has to setup permission rules on level pages. At the time rules for categories don't have effects on the page access as it seems..
Change History
comment:1 Changed 3 months ago by dipohl

Members of "Nixen" should have access to pages in category "Nixen-Intern" (ID: 10038).
Members of "Lynn" should have access to pages in category "Lynn-Intern" (ID: 10026).

I renamed the old category "Nixen-Intern" to "Lynn-Intern" and created a new category called "Nixen-Intern".

**Comment by Guite** [comment]
Closing since this issue is outdated and Pages 4.0.0 provides a complete rewrite.
