### ISSUE TITLE
Installation issues.

### ISSUE THREAD

**Issue by paustian** [zikula-modules/Pages#118]
In trying to upgrade from Pages 3.2.3 to 4.1.0 I ran into a few small issues. 

1. Line 96 of PagesModuleInstaller, the value sent to setCounter has to be cast as an int. Here is the fix:
`$page->setCounter((int)$row['counter']);`

2. Argument 1 passed to Zikula\PagesModule\Entity\Base\AbstractPageEntity::setPageLanguage() must be of the type string, bool given. The fix is:
`$page->setPageLanguage((string) $row['language']);`

Finally, after installation, it reports an invalid route for Pages. Not sure what the issue is here, but the Module is unuseable in this state. Even with a clean install I get this issue.

**Comment by Guite** [comment]
Added the small fixes in https://github.com/zikula-modules/Pages/commit/4480a81e3c04725637f9edc00de3b028e3966fcd

No idea though why it tries to create the `zikula_pages_page` table twice. Is it possible that this is only a result from your multiple test runs?

**Comment by paustian** [comment]
Yeah it was a results of the multiple test runs.

**Comment by Guite** [comment]
Thank you @paustian !

**Comment by paustian** [comment]
No route found for: Get:/pages
I left it open so you can see the results Go here
https://fourthedition.theorygizmos.com/pages
