### ISSUE TITLE
[Pages v2.6.0] Error in upgrade routine

### ISSUE THREAD

**Issue by ghost** [zikula-modules/Pages#19]
The upgrade routine changes in the case '2.4.2' the table name and removes the prefix. This is in principle ok, but some lines below DBUtil::changeTable('pages') is used and thats wrong. Because all of the DBUtil stuff uses the prefix again, which results in an upgrade error.

**Comment by craigh** [comment]
This will be solved if you upgrade to 2.5.1 first and then upgrade to 2.6.0+
