### ISSUE TITLE
Bugs in modify page

### ISSUE THREAD

**Issue by nmpetkov** [zikula-modules/Pages#25]
1, Edit puton next to category drop-down is displayed on different line.

2. Clicking on "Specific page settings" and "Meta data" does nothing, so can not see or edit respective items.

**Comment by cmfcmf** [comment]
It looks fine on the master branch, to be checked on the 2.6 branch.

**Comment by nmpetkov** [comment]
Now all is Ok, it seems it was temporary happened and connected to some javascript local problem.
