### ISSUE TITLE
Page defaults for a new page not working if creating a new page

### ISSUE THREAD

**Issue by Portugao** [zikula-modules/Pages#29]

**Comment by craigh** [comment]
this ticket makes no sense

**Comment by Portugao** [comment]
Please say why not!
For what are the page defaults if they do not work?

**Comment by shefik** [comment]
@Portugao 

Please provide more detail. What general site setting are you referring to?

**Comment by craigh** [comment]
What does "general site setting" mean? Give more information please? I have no idea what the problem is.

**Comment by Portugao** [comment]
Ok. I see. It was a misunderstandig.
I changed the issue title.

**Comment by craigh** [comment]
Please test then. I think it is fixed

**Comment by Portugao** [comment]
Not fixed in 2.6.1 (branch 2.6); sorry.

**Comment by craigh** [comment]
Please try the master branch

**Comment by Portugao** [comment]
Even not fixed in master branch.

**Comment by craigh** [comment]
Pleas explain how to reproduce the issue

**Comment by Portugao** [comment]
I checked under 1.3.9.

**Comment by Portugao** [comment]
Sorry; I'm not able to check again, because now i get with 3.0.0 an 'ORM' fault under 1.3.9:

```
Fatal error: Class 'Doctrine\ORM\Tools\Pagination\Paginator' not found in /domain/modules/Pages/lib/Pages/Access/Pages.php on line 111
```
Cannot check under 1.4.0 at the moment because i have no installation....

**Comment by craigh** [comment]
The master branch requires core 1.4

**Comment by craigh** [comment]
Pleas explain how to reproduce the problem with the 2.6 branch on core 1.3.9

**Comment by craigh** [comment]
Also please give more information about "not working". The error message is helpful.

**Comment by Portugao** [comment]
There is no error message.
If i understand correctly the settings for 'new page default' within the settings, the selected checkboxes in the settings should also be selected and the not selected checkboxes in the settings should not be selected in the edit template by creating a new page.....That does not work, if i'm right.
