### ISSUE TITLE
Link to edit is shown only on first page

### ISSUE THREAD

**Issue by Portugao** [zikula-modules/Pages#30]
If I'm administrator in the frontend i should get a link below the content to edit a page.
I get this only on the first page.

**Comment by craigh** [comment]
@Portugao please check with with >= v3.0.0-beta2 and Core-1.4.1. Also I do not know what you mean by 'first page'

**Comment by Portugao** [comment]
Which branch?

**Comment by craigh** [comment]
no branch.

https://github.com/zikula-modules/Pages/releases/tag/v3.0.0-beta2

**Comment by craigh** [comment]
plus Core 1.4.1 release

https://github.com/zikula/core/releases/download/1.4.1/Zikula_Core-1.4.1.build128.zip

**Comment by Portugao** [comment]
Ok. Sorry....

**Comment by Portugao** [comment]
Seems to work. Thx.

**Comment by Portugao** [comment]
With first page i mean, that only the page with the pageid 1 did show the edit link for admins.
This issue seems to be gone.

**Comment by craigh** [comment]
thanks!
