### ISSUE TITLE
Wrong description for 2.6 branch

### ISSUE THREAD

**Issue by nmpetkov** [zikula-modules/Pages#34]
In README.markdown for Pages 2.6 branch is writen "This version is specifially for Zikula Core 1.3.x", but in Version.php core min is 1.4.0.
It is also true for master branch.
In fact last tagged version working with Zikula 1.3.* is Pages 2.5.1.

**Comment by nmpetkov** [comment]
I tested again in Zikula 1.3.9 and still not working. It seems in Zikula 1.3.9 is missing Paginator cla
s, as the error is in this line:
https://github.com/zikula-modules/Pages/blob/2.6/lib/Pages/Access/Pages.php#L111

Is it possible to be made a branch, which is compatible with Zikula 1.3? Now seems it is impossible to download such a tagged version.

**Comment by craigh** [comment]
I tried making adjustments to the 2.6 branch. can you check it out and let me know?

**Comment by nmpetkov** [comment]
Yes, in few hours!

**Comment by nmpetkov** [comment]
Thank you, now module function, except adding new page.
After entering new page data, after pressing button to save, module fails at line:
https://github.com/zikula-modules/Pages/blob/2.6/lib/Pages/Handler/Modify.php#L107

This gives an error when adding page. Same line when editing page is fine (editing a page works).
