### ISSUE TITLE
[2.6 branch] Error creating new page

### ISSUE THREAD

**Issue by nmpetkov** [zikula-modules/Pages#42]
It is not possible to create new page, because of error.
How to reproduce:
1. Install Zikula 1.3.10 (from Github - it is same in Zikula 1.3.9 - just make new install, to be sure for "clean" results).
2. Install Pages 2.6.1 (current files from Github).
3. Go to Pages admin panel, and press "Create a page".
4 Enter title and some content, then press "Save" button.

Result:
```
Error on Site name
Error! The action you wanted to perform was not successful for some reason, maybe because of a problem with what you input. Please check and try again.
Class Zikula_Form_Plugin_CategorySelector is not a valid entity or mapped super class.
Go back to previous page
```

Selecting a category doesn't helps, the error is the same!

Please continue with the test!
5. Go to module "Settings", and disable categorization (un-check "Enable categorization" check box and save).
6. Go to "Create a page" and again enter title and some content, then press "Save" button.

Result:
```
Fatal error: Call to a member function getPageId() on a non-object in /home/xyz/public_html/zk13new/modules/Pages/lib/Pages/Access/Page.php on line 119
```

**Comment by craigh** [comment]
try back-porting this: https://github.com/zikula-modules/Pages/commit/2306b28162037b7205162d40b0bd5924a925f9d5 and see if that fixes it.

**Comment by nmpetkov** [comment]
Yes, this fixes this error.

**Comment by Portugao** [comment]
With the back-porting it works.
