### ISSUE TITLE
Install on a fresh Zikula 1.4 is not working 

### ISSUE THREAD

**Issue by phaidon** [zikula-modules/Pages#44]
Catchable Fatal Error: Argument 2 passed to Zikula\Core\Doctrine\Entity\AbstractEntityCategory::__construct() must be an instance of Zikula\Module\CategoriesModule\Entity\CategoryEntity, instance of Zikula\PagesModule\Entity\CategoryEntity given, called in src/modules/zikula/pages-module/Entity/PageEntity.php on line 564 and defined

**Comment by craigh** [comment]
master branch?

**Comment by phaidon** [comment]
yes

**Comment by phaidon** [comment]
thank you. it is working now.

**Comment by craigh** [comment]
:+1:
