### ISSUE TITLE
PageslistBlock vs PagesListBlock

### ISSUE THREAD

**Issue by phaidon** [zikula-modules/Pages#46]
Site: http://localhost/Blocks/admin/new

![mis](https://cloud.githubusercontent.com/assets/608602/8149701/c585fa70-12cd-11e5-9118-b3b318e09624.png)

Zikula\PagesModule\Block\PageslistBlock vs 
Zikula\PagesModule\Block\PagesListBlock

The class name has a big L the filename a small.

**Comment by craigh** [comment]
fixed in 
https://github.com/zikula-modules/Pages/commit/325fb5c130b7c4498235d38948e0b7df4d8e50f5
and
https://github.com/zikula-modules/Pages/commit/8667d4c307e1705983ae773cbf30feb62f939870

**Comment by phaidon** [comment]
thank you.
