### ISSUE TITLE
Initialization of ZikulaPagesModule failed

### ISSUE THREAD

**Issue by AlexL777** [zikula-modules/Pages#48]
Dear developers,

I have the module Pages 3.0.0 a problem and although I put Zikula 1.4 final version a. The module Pages I uploaded and want to install it. Which reminds me of this error appears:

    Schema-Tool failed with Error 'An exception occurred while executing 'CREATE   TABLE pages (pageid INT AUTO_INCREMENT NOT NULL, title LONGTEXT NOT NULL, metadescription LONGTEXT NOT NULL, metakeywords LONGTEXT NOT NULL, urltitle LONGTEXT NOT NULL, content LONGTEXT NOT NULL, counter INT NOT NULL, displaywrapper TINYINT(1) NOT NULL, displaytitle TINYINT(1) NOT NULL, displaycreated TINYINT(1) NOT NULL, displayupdated TINYINT(1) NOT NULL, displaytextinfo TINYINT(1) NOT NULL, displayprint TINYINT(1) NOT NULL, language VARCHAR(30) NOT NULL, cr_date DATETIME NOT NULL, lu_date DATETIME NOT NULL, obj_status VARCHAR(1) NOT NULL, cr_uid INT DEFAULT NULL, lu_uid INT DEFAULT NULL, INDEX IDX_2074E5758304AF18 (cr_uid), INDEX IDX_2074E575C072C1DD (lu_uid), PRIMARY KEY(pageid)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = innodb': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'pages' already exists' while executing DDL: CREATE TABLE pages (pageid INT AUTO_INCREMENT NOT NULL, title LONGTEXT NOT NULL, metadescription LONGTEXT NOT NULL, metakeywords LONGTEXT NOT NULL, urltitle LONGTEXT NOT NULL, content LONGTEXT NOT NULL, counter INT NOT NULL, displaywrapper TINYINT(1) NOT NULL, displaytitle TINYINT(1) NOT NULL, displaycreated TINYINT(1) NOT NULL, displayupdated TINYINT(1) NOT NULL, displaytextinfo TINYINT(1) NOT NULL, displayprint TINYINT(1) NOT NULL, language VARCHAR(30) NOT NULL, cr_date DATETIME NOT NULL, lu_date DATETIME NOT NULL, obj_status VARCHAR(1) NOT NULL, cr_uid INT DEFAULT NULL, lu_uid INT DEFAULT NULL, INDEX IDX_2074E5758304AF18 (cr_uid), INDEX IDX_2074E575C072C1DD (lu_uid), PRIMARY KEY(pageid)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = innodb

How can I remove it or install the module well?

About a help I would of course be very happy. Thank you in advance.

**Comment by craigh** [comment]
Pages 3.0.0 is not released. please do not use development software. Please use Pages 2.6.0

https://github.com/zikula-modules/Pages/releases
