### ISSUE TITLE
Fatal Error Exception when calling hooks settings

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Pages#51]
I installed Pages-master. Scribite-master (5.0.1) is available. But Pages is telling me during installtion scribite is missing.

Not a big issue but will lead to support work if not fixed.

**Comment by rallek** [comment]
Now it becomes a bigger issue. If I try to open the hook setting I do get the following error:
````

Whoops, looks like something went wrong.
1/1 FatalErrorException in AdminController.php line 1627: Error: Call to a member function getHookSubscriberBundle() on a non-object

    in AdminController.php line 1627

````

**Comment by rallek** [comment]
even if I try to change the hook inside scribite I do get a similar error. Deleting pages the hook link inside scribite is working again.
This one makes pages unusable.

**Comment by craigh** [comment]
This is fixed.
