### ISSUE TITLE
Categories are not show when german language is main language

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Pages#53]
I do have an installation with languages (english/german). If the main language is english, the selected categories are show. If it is german, the categories are empty.

See also #52

**Comment by craigh** [comment]
I'm guessing not actually empty, just an empty translation. So the category assignment exists, but you cannot see it because there is no text. but this is just a guess.

**Comment by rallek** [comment]
If this is true, the fall back is not working in case there is no translation in the category definition

**Comment by Guite** [comment]
Closing since this issue is outdated and Pages 4.0.0 provides a complete rewrite.
