### ISSUE TITLE
Cannot install Pages Module under Zikula 1.4.6 - this Errors

### ISSUE THREAD

**Issue by AlexL777** [zikula-modules/Pages#65]
Hello Developers,

Unfortunately I can not install "Pages" under Zikula 1.4.6. After clicking "Install", I see these errors.

`Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
An exception occurred while executing 'INSERT INTO pages (title, metadescription, metakeywords, urltitle, content, counter, displaywrapper, displaytitle, displaycreated, displayupdated, displaytextinfo, displayprint, language, cr_date, lu_date, obj_status, cr_uid, lu_uid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["Welcome to Pages content manager", "", "", "welcome-to-pages-content-manager", "This is a demonstration page. You can use Pages to create simple static content pages. It is excellent if you only need basic html for your pages. You can also utilize the Scribite module for WYSIWYG content creation. It is well suited for informational articles, documents and other \"long term\" type content items.<br \/><br \/>Pages is a hookable module which allows you to hook EZComments or other hook providers to extend the capabilities of your module.", 0, 1, 1, 1, 1, 1, 1, "en", null, null, "A", null, null]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'cr_date' cannot be null`

I have already downloaded the master branch, but the same error. Can you please take a look with the last Zikula version.

Thanks in advance.

**Comment by AlexL777** [comment]
This was a hard birth with the installation of Pages Module, but I have successfully implemented it. I had to run again and again in the MySQL database "drop tables pages" and then the installation tried again and again.

Now I just have to test the pages.

The installation of knowledgebase still remains, which also shows errors.

**Comment by craigh** [comment]
I wouldn't bother with knowledgebase.

are you using MySQL?

**Comment by AlexL777** [comment]
OK,
So, I made deleting the tables directly using an SQL query in the database. It did not work.

Too bad, but maybe someone wants to see the knowledgebase module :smile:

**Comment by AlexL777** [comment]
Unfortunately I have problems with the installation of pages this time. These errors are displayed.

`An exception occurred while executing 'INSERT INTO pages (title, metadescription, metakeywords, urltitle, content, counter, displaywrapper, displaytitle, displaycreated, displayupdated, displaytextinfo, displayprint, language, cr_date, lu_date, obj_status, cr_uid, lu_uid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["Welcome to Pages content manager", "", "", "welcome-to-pages-content-manager", "This is a demonstration page. You can use Pages to create simple static content pages. It is excellent if you only need basic html for your pages. You can also utilize the Scribite module for WYSIWYG content creation. It is well suited for informational articles, documents and other \"long term\" type content items.<br \/><br \/>Pages is a hookable module which allows you to hook EZComments or other hook providers to extend the capabilities of your module.", 0, 1, 1, 1, 1, 1, 1, "en", null, null, "A", null, null]:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'cr_date' cannot be null`

This is again the same problem and I try again and again to install. Server is Ubuntu with PHP 5.6 and MySQL 5.6. Module version is the last one that should be compatible with Zikula 1.4.

**Comment by Guite** [comment]
Closing since this issue is outdated and Pages 4.0.0 provides a complete rewrite.
