### ISSUE TITLE
Search leads into error message

### ISSUE THREAD

**Issue by Portugao** [zikula-modules/Pages#66]
If I try a search in SearchModule I get this error:
```
UndefinedMethodException in SearchHelper.php line 64:
Attempted to call an undefined method named "getCategories" of class "Zikula\PagesModule\Entity\PageEntity".
```
Zikula 1.4.6
Php 5.6

**Comment by craigh** [comment]
what version of pages are you using?

**Comment by Portugao** [comment]
3.1.0

**Comment by craigh** [comment]
This (specific) issue is corrected in master, but other issues remain with Pages and search that I am looking into.

**Comment by Portugao** [comment]
Thank you.
